[package]
name = "CouponsWorld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.0"
mongodb = "2.3.0"
serde = { version = "1.0", features = ["derive"] }
